services:
  mpm-smart-web:
    image: mpm-smart-web
    build:
      context: .
      dockerfile: Mpm-Smart-Web/Mpm-Smart-Web/Dockerfile

  mpm-smart-web.client:
    image: mpm-smart-web.client
    build:
      context: .
      dockerfile: Mpm-Smart-Web/Mpm-Smart-Web.Client/Dockerfile

  web.api:
    image: web.api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile

  dbmanager:
    image: dbmanager
    build:
      context: .
      dockerfile: DbManager/Dockerfile

  networkservice:
    image: networkservice
    build:
      context: .
      dockerfile: NetworkService/Dockerfile

  routineservice:
    image: routineservice
    build:
      context: .
      dockerfile: RoutineService/Dockerfile

  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  commandservice:
    image: commandservice
    build:
      context: .
      dockerfile: CommandService/Dockerfile

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile

  homedataservice:
    image: homedataservice
    build:
      context: .
      dockerfile: HomeDataService/Dockerfile

  admindashboard:
    image: admindashboard
    build:
      context: .
      dockerfile: AdminDashboard/Dockerfile
