---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: localhost:5001/mpm/authservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: authservice-env
        - secretRef:
            name: authservice-secrets
      terminationGracePeriodSeconds: 180