---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandservice
  labels:
    app: commandservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
      - name: commandservice
        image: localhost:5001/mpm/commandservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: commandservice-env
        - secretRef:
            name: commandservice-secrets
      terminationGracePeriodSeconds: 180