---
apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  type: ClusterIP
  selector:
    app: maildev
  ports:
  - name: http
    port: 9324
    targetPort: 1080
  - name: smtp
    port: 9325
    targetPort: 1025
