---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
  - name: http
    port: 9326
    targetPort: 7474
  - name: neo4j
    port: 9327
    targetPort: 7687
