resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sql-env
  literals:
    - ACCEPT_EULA=Y
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=sql

secretGenerator:
- name: sql-secrets
  envs:
  - .sql.secrets
