---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
      - name: notificationservice
        image: localhost:5001/mpm/notificationservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: notificationservice-env
        - secretRef:
            name: notificationservice-secrets
      terminationGracePeriodSeconds: 180