---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: localhost:5001/mpm/web-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: web-server-env
      terminationGracePeriodSeconds: 180