---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  type: ClusterIP
  selector:
    app: web-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
