---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkservice
  labels:
    app: networkservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: networkservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: networkservice
    spec:
      containers:
      - name: networkservice
        image: localhost:5001/mpm/networkservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: networkservice-env
        - secretRef:
            name: networkservice-secrets
      terminationGracePeriodSeconds: 180