---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routineservice
  labels:
    app: routineservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: routineservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: routineservice
    spec:
      containers:
      - name: routineservice
        image: localhost:5001/mpm/routineservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: routineservice-env
        - secretRef:
            name: routineservice-secrets
      terminationGracePeriodSeconds: 180