---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagateway
  labels:
    app: datagateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: datagateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datagateway
    spec:
      containers:
      - name: datagateway
        image: localhost:5001/mpm/datagateway:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: datagateway-env
        - secretRef:
            name: datagateway-secrets
      terminationGracePeriodSeconds: 180