---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:7.2
          imagePullPolicy: Always
          args:
            - '--save'
            - '60'
            - '1'
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis-env
          volumeMounts:
            - name: web-host-redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: web-host-redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
