# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: [9.x]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Tasks
      run: dotnet build --no-restore src/build-tasks/ReadJsonFileTask/ReadJsonFileTask.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Remove Template Folder
      run: rm -rf build/plugins/test-plugin
    - name: Create Test Plugin Folder
      run: mkdir -p build/plugins/mpm-test-plugin
    - name: Copy Test Plugin
      run: cp src/controller/plugins/test-plugin/bin/Debug/net9.0/TestPlugin.dll build/plugins/mpm-test-plugin/TestPlugin.dll
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: [9.x]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      run: nohup dotnet run --project src/controller/control_process/ControlProcess.csproj > backend.log 2>&1 &
    - name: Wait
      run: sleep 20
    - name: Log
      run: cat backend.log
